### ISSUE TITLE
项目报错

### ISSUE THREAD

**Issue by zhaokailin** [Famine-Life/Lbook#2]
[图片]

**Comment by zhaokailin** [comment]
SQL: SELECT *         FROM orders             NATURAL JOIN (                 SELECT  name AS bookname,                         author,ISBN,                         price,                         cover                 FROM books ) AS bookss             NATURAL JOIN (                 SELECT  name AS username,                         account                 FROM users ) AS users               WHERE account = ?         ORDER BY id desc
### Cause: java.sql.SQLSyntaxErrorException: Unknown column 'cover' in 'field list'
; bad SQL grammar []; nested exception is java.sql.SQLSyntaxErrorException: Unknown column 'cover' in 'field list'] with root cause

java.sql.SQLSyntaxErrorException: Unknown column 'cover' in 'field list'

**Comment by Famine-Life** [comment]
整好了么，，没好加vx：xanwidtf



---原始邮件---
发件人: "zhaokailin"<notifications@github.com&gt;
发送时间: 2019年11月4日(星期一) 下午2:05
收件人: "Famine-Life/Lbook"<Lbook@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: Re: [Famine-Life/Lbook] 项目报错 (#2)



SQL: SELECT *         FROM orders             NATURAL JOIN (                 SELECT  name AS bookname,                         author,ISBN,                         price,                         cover                 FROM books ) AS bookss             NATURAL JOIN (                 SELECT  name AS username,                         account                 FROM users ) AS users               WHERE account = ?         ORDER BY id desc
 
Cause: java.sql.SQLSyntaxErrorException: Unknown column 'cover' in 'field list'
 
; bad SQL grammar []; nested exception is java.sql.SQLSyntaxErrorException: Unknown column 'cover' in 'field list'] with root cause
 
java.sql.SQLSyntaxErrorException: Unknown column 'cover' in 'field list'
